FROM node:20-alpine

RUN npm install -g typescript \
    && apk add --no-cache curl \
    && curl -# -L https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc \
    && chmod +x /usr/local/bin/mc

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

RUN rm package.json yarn.lock

CMD ["node", "--version"]
