/**
 * Clean records duplicated by repeated runs of seed-vetinh-content.ts.
 *
 * v2's POST endpoint disambiguates duplicate slugs by appending `-2`, `-3`, …
 * so each extra seed run produced one extra row per source record. Heuristic:
 *   For every slug ending in `-<N>` (N ≥ 2), if a sibling row exists in the
 *   same collection scope (same logical entity + same tenant) with the slug
 *   stripped of the `-<N>` suffix → delete the `-<N>` row.
 *
 * Scope:
 *   - post-type-content (logical: tin-tuc, san-pham, chinh-sach) — group key: collection_name
 *   - category                                                   — group key: post_type (if exists)
 *   - page                                                       — group key: (none, just slug)
 *
 * Usage:
 *   npx tsx scripts/clean-seed-duplicates.ts --tenant vang-thien-long --dry-run
 *   npx tsx scripts/clean-seed-duplicates.ts --tenant vang-thien-long
 */

import 'dotenv/config';
import { MongoClient } from 'mongodb';

const MAIN_URI =
  process.env.MONGODB_URL ||
  'mongodb://thaily:Th%40i2004@localhost:10000/mangoads?authSource=admin&replicaSet=rs0&directConnection=true';

interface Args {
  tenant?: string;
  dryRun: boolean;
}

function parseArgs(): Args {
  const args: Args = { dryRun: false };
  for (let i = 2; i < process.argv.length; i++) {
    const v = process.argv[i];
    if (v === '--dry-run') args.dryRun = true;
    else if (v === '--tenant') args.tenant = process.argv[++i];
  }
  return args;
}

const SUFFIX_RE = /-(\d+)$/;

/** strip `-2`, `-3`, … off end of slug. Returns null when no suffix. */
function stripSuffix(slug: string): { base: string; n: number } | null {
  const m = SUFFIX_RE.exec(slug);
  if (!m) return null;
  const n = Number(m[1]);
  if (n < 2) return null; // -1 isn't generated by v2; defensive
  return { base: slug.slice(0, -m[0].length), n };
}

interface CleanResult {
  collection: string;
  scanned: number;
  deleted: number;
  skipped: number;
}

async function cleanCollection(
  db: any,
  collectionName: string,
  scopeFields: string[],
  dryRun: boolean,
): Promise<CleanResult> {
  const coll = db.collection(collectionName);

  // Find candidate rows whose slug ends in -<N>
  const candidates = await coll
    .find({ slug: { $regex: '-\\d+$' } })
    .project({ _id: 1, slug: 1, ...Object.fromEntries(scopeFields.map((f) => [f, 1])) })
    .toArray();

  let deleted = 0;
  let skipped = 0;
  for (const c of candidates) {
    const stripped = stripSuffix(c.slug);
    if (!stripped) {
      skipped++;
      continue;
    }
    // Build filter: same base slug + same scope fields
    const filter: any = { slug: stripped.base };
    for (const f of scopeFields) {
      if (c[f] !== undefined) filter[f] = c[f];
    }
    const base = await coll.findOne(filter);
    if (!base) {
      // No base row exists → this `-2` row is the actual canonical one; keep it.
      skipped++;
      continue;
    }
    if (dryRun) {
      console.log(`  - drop ${c._id} slug=${c.slug} (base exists: ${base._id})`);
    } else {
      await coll.deleteOne({ _id: c._id });
    }
    deleted++;
  }

  return { collection: collectionName, scanned: candidates.length, deleted, skipped };
}

async function main() {
  const args = parseArgs();
  console.log(`Mode: ${args.dryRun ? 'DRY RUN' : 'LIVE'}${args.tenant ? ` (tenant ${args.tenant})` : ''}\n`);

  const m = new MongoClient(MAIN_URI);
  await m.connect();

  const tenantFilter: any = args.tenant ? { slug: args.tenant } : {};
  const tenants = await m.db().collection('tenant').find(tenantFilter).toArray();

  for (const t of tenants) {
    const uri = t.database?.uri;
    if (!uri || t.database?.type !== 'mongodb') {
      console.log(`[${t.slug}] not a MongoDB tenant — skipping`);
      continue;
    }
    console.log(`=== ${t.slug} ===`);

    const client = new MongoClient(uri);
    await client.connect();
    const db = client.db();

    // Map collection → scope fields (slug must be unique within scope)
    const targets: Array<{ name: string; scope: string[] }> = [
      { name: 'post-type-content', scope: ['collection_name', 'locale'] },
      { name: 'category', scope: ['post_type', 'locale'] },
      { name: 'page', scope: ['locale'] },
    ];

    for (const tgt of targets) {
      const exists = (await db.listCollections({ name: tgt.name }).toArray()).length > 0;
      if (!exists) continue;
      const result = await cleanCollection(db, tgt.name, tgt.scope, args.dryRun);
      console.log(
        `  ${result.collection.padEnd(22)} scanned=${result.scanned} deleted=${result.deleted}${result.skipped ? ` skipped=${result.skipped}` : ''}`,
      );
    }

    await client.close();
    console.log();
  }

  await m.close();
  console.log('Done.');
}

main().catch((e) => {
  console.error('FAILED:', e);
  process.exit(1);
});
